// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ2VtnGoxnQSsVEh4XeDXOSy3Mrg2SLnI',
    appId: '1:1050024735473:android:53dbbf2ab1d67b83372f50',
    messagingSenderId: '1050024735473',
    projectId: 'aprendendo-flutter-e536c',
    storageBucket: 'aprendendo-flutter-e536c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9ESEMIeZfVoANCsj069z29eDjp5xzVQI',
    appId: '1:1050024735473:ios:854befc8e49f0c58372f50',
    messagingSenderId: '1050024735473',
    projectId: 'aprendendo-flutter-e536c',
    storageBucket: 'aprendendo-flutter-e536c.firebasestorage.app',
    androidClientId: '1050024735473-04tifjhsb68i6lf9nl3kd45cbg43lkir.apps.googleusercontent.com',
    iosBundleId: 'com.airtonsiq.aprendendoflutter.aprendendoFlutter',
  );
}
